-- -----------------------------------------------------------------------------
-- COMMONS Tables 
-- Common tables for Config, Logging management
-- -----------------------------------------------------------------------------

--
-- COMMONS_LOG_CONFIG, Index Organized Table
--
create table perfcomp.commons_log_config
(
    owner                   VARCHAR2(30),
    module_name             VARCHAR2(30),
    component_name          VARCHAR2(30),
    log_info_verbose_flg    CHAR(1),
    log_info_terse_flg      CHAR(1),
    --
    createdby               VARCHAR2(255),
    createddate             DATE,
    modifiedby              VARCHAR2(255),
    modifieddate            DATE,
    auditosuser             VARCHAR2(30),
    audithost               VARCHAR2(60)
);

alter table perfcomp.commons_log_config add constraint commons_log_config_pk
primary key (owner, module_name, component_name);


-- 
-- Table commons_error_log
-- 
create table commons_error_log
(
  error_log_id          number(22)        generated by default as identity (start with 1 increment by 1),
  component_name        varchar2(30)      not null,
  module_name           varchar2(256)     not null,
  job_number            varchar2(30),
  log_date              date,
  log_datetime_local    date,
  log_datetime_gmt      date,
  username              varchar2(30)      not null,
  osuser                varchar2(30)      not null,
  audithost             varchar2(60)      not null,
  error_message         varchar2(4000),
  ora_error_message     varchar2(4000)
)
partition by range (LOG_DATE)
interval (numtoyminterval(1,'MONTH'))
(
   partition ip1 values less than (to_date('01-JAN-2017','DD-MON-YYYY'))
);

create index commons_error_log_main_idx on commons_error_log(COMPONENT_NAME, MODULE_NAME,JOB_NUMBER) local;
create index commons_error_log_logdate_idx on commons_error_log(LOG_DATE) local;



--
-- Table commons_audit_log
--
create table commons_audit_log
(
  audit_log_id          number(22) generated by default as identity (start with 1 increment by 1),
  component_name        varchar2(30)      not null,
  module_name           varchar2(30)     not null,
  job_number            varchar2(30),
  log_date              date,
  log_datetime_local    date,
  log_datetime_gmt      date,
  username              varchar2(30)      not null,
  osuser                varchar2(30)      not null,
  audithost             varchar2(60)      not null,
  audit_message         varchar2(4000)    not null
)
partition by range (LOG_DATE)
interval (numtoyminterval(1,'MONTH'))
(
   partition ip1 values less than (to_date('01-JAN-2017','DD-MON-YYYY'))
);

create index commons_audit_log_main_idx on commons_audit_log(COMPONENT_NAME, MODULE_NAME,JOB_NUMBER) local;
create index commons_audit_log_logdate_idx on commons_audit_log(LOG_DATE) local;
